apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
    - name: config-map-volume
      configMap:
        name: my-config-map
  containers:
    - name: nginx
      image: public.ecr.aws/nginx/nginx:1.23
      ports:
      - name: http
        containerPort: 80
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
        - name: config-map-volume
          readOnly: true
          mountPath: "/etc/config-map-volume"